---
- name: Install java, net-tools
  hosts: webservers
  become: yes
  tasks:
      - name: update apt repo & cache
        apt: 
          update_cache: yes
          force_apt_get: yes
          cache_valid_time: 3600
      - name: install java 8, net-tools
        apt: 
          pkg: 
            - openjdk-8-jre-headless
            - net-tools

- name: Download & unpack nexus
  hosts: webservers
  become: yes
  tasks:
    - name: check if nexus folder already exists
      stat:
        path: /opt/nexus
      register: stat_result
    - name: Download nexus
      get_url: 
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result

    - name: unarchive tar file
      unarchive: 
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
      when: not stat_result.stat.exists
    - name: find nexus folder
      find: 
        paths: /opt/
        pattern: "nexus-*"
        file_type: directory
      register: var_find_folder_name
    - name: rename nexus folder to nexus
      shell: mv {{var_find_folder_name.files[0].path}} /opt/nexus
      when: not stat_result.stat.exists

- name: create nexus user to own nexus folders
  hosts: webservers
  become: yes
  tasks:
    - name: ensure group nexus already exists / create nexus group
      group: 
        name: nexus
        state: present
    - name: create user nexus
      user:
        name: nexus
        comment: Nexus User ANSIBLE
        state: present
        group: nexus
    - name: Make nexus user owner of nexus folder
      file: 
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: Make nexus user owner of sonatype-work folder
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes

- name: Start nexus with nexus user
  hosts: webservers
  become: yes
  become_user: nexus
  tasks:
    - name: Set run_as_user in nexus.rc file to nexus user
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regexp: '^#run_as_user='
        line: run_as_user="nexus"
    - name: Start nexus
      command: /opt/nexus/bin/nexus start
      async: 1000
      poll: 0
  
- name: Verify Nexus is running
  hosts: webservers
  tasks:
  - name: Ensure Nexus is running, check with ps
    shell: ps aux | grep nexus
    register: v_nexus_status
  - debug: msg={{v_nexus_status.stdout_lines}}
  - name: Wait for port 8081 to open for Nexus web-access for 30 seconds
    wait_for:
      timeout: 10
  - name: Ensure Nexus is running, check with netstat
    shell: netstat -plnt
    register: v_nexus_status
  - debug: msg={{v_nexus_status.stdout_lines}}