---
  - name: install nodejs & npm
    hosts: webservers
    become: yes
    become_user: vikas
    tasks:
      - name: update apt repo & cache
        apt: 
          update_cache: yes
          force_apt_get: yes
          cache_valid_time: 3600
      - name: Install nodejs & npm
        apt:
          pkg:
            - nodejs
            - npm