---
  - name: install nodejs & npm
    become: yes
    hosts: webservers
    tasks:
      - name: update apt repo & cache
        apt: 
          update_cache: yes
          force_apt_get: yes
          cache_valid_time: 3600
      - name: Install nodejs & npm
        apt:
          pkg:
            - nodejs
            - npm

  - name: Create a new user for node app
    become: yes
    hosts: webservers
    tasks:
      - name: Create linux user
        user: 
          name: pandey
          comment: pandey admin
          group: admin

  - name: deploy node js app
    hosts: webservers
    become: True
    tasks:
      - name: unpack node js tar file from local to remote
        ansible.builtin.unarchive:
          src: /mnt/c/Users/vikas/OneDrive/Desktop/P/Node/hello-world-1/hello-world-1-1.0.0.tgz
          dest: /home/pandey/
      - name: install dependencies
        npm:
          path: /home/pandey/package
      - name: run the node app 
        command:
          chdir: /home/pandey/package/app
          cmd: node server
        async: 1000
        poll: 0
      - name: ensure the app is running
        shell: ps aux | grep node
        register: node_app_status
      - debug: msg={{node_app_status.stdout_lines}}